# Generated by Django 5.0.6 on 2024-05-11 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('bank_code', models.CharField(default='', max_length=10, primary_key=True, serialize=False)),
                ('bank_name', models.CharField(default='', max_length=100)),
                ('legal_address', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ATM',
            fields=[
                ('atm_number', models.CharField(default='', max_length=10, primary_key=True, serialize=False)),
                ('address', models.CharField(default='', max_length=255)),
                ('bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.bank')),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('card_number', models.CharField(default='', max_length=20, primary_key=True, serialize=False)),
                ('full_name', models.CharField(default='', max_length=255)),
                ('address', models.CharField(default='', max_length=255)),
                ('bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.bank')),
            ],
        ),
        migrations.CreateModel(
            name='Operations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('commission', models.BooleanField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('atm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.atm')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.clients')),
            ],
        ),
    ]
