# Generated by Django 5.0.6 on 2024-06-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_atm_operations_atm_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operations',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
