# Generated by Django 5.0.6 on 2024-06-28 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_operations_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operations',
            name='commission',
        ),
    ]
