# Generated by Django 5.0.6 on 2024-06-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_operations_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='operations',
            name='comission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
