# Generated by Django 5.0.6 on 2024-07-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_operations_comission'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='account',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
