# Generated by Django 5.0.6 on 2024-07-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_clients_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='operations',
            name='add_take',
            field=models.BooleanField(default=True),
        ),
    ]
