# Generated by Django 5.0.6 on 2024-07-30 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_bank_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='operations',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='operations',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
