# Generated by Django 5.0.6 on 2024-07-30 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_operations_price_alter_operations_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operations',
            name='price',
        ),
    ]
